-- AlterTable
ALTER TABLE `clock` MODIFY `clockInTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `clockOutTime` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `statusClockIn` ENUM('ONTIME', 'LATE') NOT NULL DEFAULT 'ONTIME';
